### ISSUE TITLE
To Do for Dec 15 deliverable

### ISSUE THREAD

**Issue by amcphe30** [amcphe30/Oracle-of-Delphi#5]
## Description
Some version of this project must be handed in on Dec 15. It does not need to be entirely complete but there are some things that must be done in order to fit the rubric I wrote for myself when submitting the concept. I will be putting off the syntax tests for the time being since I need to focus on an MVP and test coverage is not included in this deliverable. It will be my primary focus after these tasks are complete.

### Roadmap
- [x] Frontend progress through question tree, seeker 1 asks a questions, answered, responds, next seeker comes up
- [ ] Game does something relatively elegant when all seekers are out of questions
- [x] Non-test data for question tree and list of advice seekers
- [x] Seeker image is reflects the current seeker asking or responding to the Oracle
- [x] Deployed in some fashion, barring that (since I've never done it and I don't know how complicated it will be), a video demonstration
- [x] Doc accompanying the game detailing process, challenges, where I want to take it from here, demonstration of research, sources, still images from the game, link and instructions or video depending on task above 

### Time Estimate
1. Frontend progresses - 1 hour
2. Game over process - 45 mins
3. Non-test data - 2 hours
4. Seeker image is dynamic and accurate - 1.5 hours
5. Deployment/video - 3 hours
6. Accompanying doc - 4 hours
Total = 11.25 hours + buffer = 13 hours

### Time Actual
1. Frontend progresses - 1 hr
2. Non-test data - 1 hr
3. Seeker image is dynamic and accurate - .5 hours
4. Accompanying doc - 2 hr (ongoing)
